################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BayesFunctions/BayesFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BayesFunctions/BayesFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/CommonTables/CommonTables.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/CommonTables/CommonTablesF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ComplexMathFunctions/ComplexMathFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ComplexMathFunctions/ComplexMathFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/InterpolationFunctions/InterpolationFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/InterpolationFunctions/InterpolationFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/MatrixFunctions/MatrixFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/MatrixFunctions/MatrixFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions/QuaternionMathFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SVMFunctions/SVMFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SVMFunctions/SVMFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SupportFunctions/SupportFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SupportFunctions/SupportFunctionsF16.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/TransformFunctions/TransformFunctions.c \
C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/TransformFunctions/TransformFunctionsF16.c 

OBJS += \
./Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/CommonTables.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/CommonTablesF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/ControllerFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctionsF16.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctions.o \
./Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctionsF16.o 

C_DEPS += \
./Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/CommonTables.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/CommonTablesF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/ControllerFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctionsF16.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctions.d \
./Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctionsF16.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BasicMathFunctions/BasicMathFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/BasicMathFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BayesFunctions/BayesFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/BayesFunctions/BayesFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/BayesFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/CommonTables.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/CommonTables/CommonTables.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/CommonTables.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/CommonTablesF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/CommonTables/CommonTablesF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/CommonTablesF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ComplexMathFunctions/ComplexMathFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ComplexMathFunctions/ComplexMathFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/ComplexMathFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/ControllerFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/ControllerFunctions/ControllerFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/ControllerFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/DistanceFunctions/DistanceFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/DistanceFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FastMathFunctions/FastMathFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/FastMathFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/FilteringFunctions/FilteringFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/FilteringFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/InterpolationFunctions/InterpolationFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/InterpolationFunctions/InterpolationFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/InterpolationFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/MatrixFunctions/MatrixFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/MatrixFunctions/MatrixFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/MatrixFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions/QuaternionMathFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/QuaternionMathFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SVMFunctions/SVMFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SVMFunctions/SVMFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/SVMFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/StatisticsFunctions/StatisticsFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/StatisticsFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SupportFunctions/SupportFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/SupportFunctions/SupportFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/SupportFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctions.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/TransformFunctions/TransformFunctions.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctions.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctionsF16.o: C:/Users/frank/OneDrive/Documents/seniorDesign/seniorProject/test/Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Source/TransformFunctions/TransformFunctionsF16.c Middlewares/CMSIS/CMSIS/DSP/Source/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DDEBUG -DCORE_CM7 -DUSE_HAL_DRIVER -DSTM32H755xx -c -I../Core/Inc -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include -I../../Drivers/STM32H7xx_HAL_Driver/Inc -I../../Drivers/STM32H7xx_HAL_Driver/Inc/Legacy -I../../Drivers/CMSIS/Device/ST/STM32H7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/Core_A/Include/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/PrivateInclude/ -I../../Middlewares/Third_Party/ARM_CMSIS/CMSIS/DSP/Include/ -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/CMSIS/CMSIS/DSP/Source/TransformFunctionsF16.d" -MT"$@" --specs=nano.specs -mfpu=fpv5-d16 -mfloat-abi=hard -mthumb -o "$@"

